discord:
  bot_token:
telegram: XiaomiFirmware
  bot_token: 1365237681:AAGJMZP5nRRNtfues5nN5bVVEVqwo4DezE8
  chat: MIUIUpdatesTracker
twitter:
  consumer_key:
  consumer_secret:
  access_token:
  access_token_secret:
facebook:
  page_id:
  page_token:
git_oauth_token:
source: tracker_official
